services:
  - type: web
    name: cafe-fausse-frontend
    env: static
    rootDir: cafe-fausse-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://cafe-fausse-p7er.onrender.com